modLoader="javafml"
loaderVersion="[46,)"
license="LGPL-3.0"
[[mods]]
modId="timestopper"
version="0.10"
displayName="Time Stopper"
displayURL="https://przemyk.xyz/"
authors="Przemyk"
description='''
This mod adds time stopper.
'''
[[dependencies.timestopper]]
    modId="forge"
    mandatory=true
    versionRange="[46,)"
    ordering="NONE"
    side="BOTH"
[[dependencies.timestopper]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.20,1.21)"
    ordering="NONE"
    side="BOTH"
